### ISSUE TITLE
Phoneix Wright Ace Attorney

### ISSUE THREAD

**Issue by skrll4x3** [Kaplas80/TF3#22]
Hi kaplas, Are you considering an update for phoneix wright ace attorney? i tried to use to it translation framework 2.0 but i think it doesnt work anymore. if your answer no, do u know any tool for pwaa steam edition ? sorry for asking like this way .

**Comment by Kaplas80** [comment]
Hello!

No, that game is not in my future plans. As you say, in TF2 I did it wrong and it doesn't work well, and the guy who was going to translate it to Spanish abandoned the project, so I stopped developing it.

I think there are other tools to translate, because other group [translated the game to Spanish](https://tradusquare.es/proyectos/aa-trilogy/), but I don't know if those tools are publicly available.

**Comment by skrll4x3** [comment]
Thanks for answering Kaplas ! Thanks to your works, yakuza 0 was translated into Turkish .I wish i could same thing for Phoenix Wright. I hope all goes well with you.
